# %% [markdown]
# ## 6. Feature Importance Analysis
# 
# Since `overall_feeling` was generated by the same LLM call as the other dimensions, this section models the LLM's internal consistency — which experiential factors does it weigh most when forming an overall impression? This isn't predicting human preferences; it's reverse-engineering how the model synthesizes a holistic rating from component scores.

# %%
from scipy.stats import spearmanr
from sklearn.feature_selection import mutual_info_regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
import shap

X = df[FEATURE_COLS]
y = df['overall_feeling']

# 6a. Spearman Correlation
spearman_scores = pd.Series({col: spearmanr(X[col], y).correlation for col in FEATURE_COLS}).abs()

# 6b. Mutual Information
mi_scores = pd.Series(mutual_info_regression(X, y, random_state=42), index=FEATURE_COLS)

# 6c. Random Forest Feature Importance
rf = RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X, y)
rf_scores = pd.Series(rf.feature_importances_, index=FEATURE_COLS)

# 6d. Permutation Importance
perm_result = permutation_importance(rf, X, y, n_repeats=20, random_state=42, n_jobs=-1)
perm_scores = pd.Series(perm_result.importances_mean, index=FEATURE_COLS)

# 6e. Consolidated Ranking
ranks = pd.DataFrame({
    'Spearman Rank': spearman_scores.rank(ascending=False),
    'MI Rank': mi_scores.rank(ascending=False),
    'RF Rank': rf_scores.rank(ascending=False),
    'Perm Rank': perm_scores.rank(ascending=False)
})
ranks['Avg Rank'] = ranks.mean(axis=1)
ranks_sorted = ranks.sort_values('Avg Rank')

print("Consolidated Feature Importance Ranking (Top 10):")
display(ranks_sorted.head(10).round(2))

# Visualization
fig, axes = plt.subplots(2, 2, figsize=(18, 14))
axes = axes.flatten()

methods = [('Spearman Correlation (abs)', spearman_scores), 
           ('Mutual Information', mi_scores), 
           ('RF Impurity Importance', rf_scores), 
           ('Permutation Importance', perm_scores)]

for i, (title, scores) in enumerate(methods):
    top15 = scores.sort_values(ascending=False).head(15)
    sns.barplot(x=top15.values, y=[col.replace('_', ' ').title() for col in top15.index], ax=axes[i], color=ACCENT_COLORS[i])
    axes[i].set_title(title)

plt.tight_layout()
plt.show()

# %% [markdown]
# **Observation:** All methods agree that `impactful`, `immersive`, and `plot_quality_rating` are the strongest drivers. This consensus gives us confidence in our understanding of what features are most critical to the `overall_feeling`.

# %% [markdown]
# ## 7. Modeling `overall_feeling`
# 
# We'll use a 4-stage model pipeline from simple to complex to predict `overall_feeling` and extract a readable formula.

# %%
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.linear_model import LinearRegression, ElasticNetCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import xgboost as xgb

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

models = {}

# Stage 1: OLS Linear Regression
ols = LinearRegression()
ols.fit(X_train, y_train)
models['OLS'] = ols

# Stage 2: ElasticNet
elastic = ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9], cv=5, random_state=42)
elastic.fit(X_train, y_train)
models['ElasticNet'] = elastic

# Stage 3: XGBoost
xgb_model = xgb.XGBRegressor(n_estimators=300, max_depth=5, learning_rate=0.1, random_state=42, verbosity=0)
xgb_model.fit(X_train, y_train)
models['XGBoost'] = xgb_model

# Stage 4: Symbolic Regression
try:
    from gplearn.genetic import SymbolicRegressor
    sr = SymbolicRegressor(
        population_size=2000,
        generations=20,
        tournament_size=20,
        stopping_criteria=0.01,
        p_crossover=0.7,
        p_subtree_mutation=0.1,
        p_hoist_mutation=0.05,
        p_point_mutation=0.1,
        max_samples=0.9,
        verbose=0,
        parsimony_coefficient=0.01,
        random_state=42,
        function_set=['add', 'sub', 'mul', 'div']
    )
    sr.fit(X_train, y_train)
    models['Symbolic'] = sr
except ImportError:
    print('gplearn not installed. Skip symbolic regression.')

# Evaluate Models
results = []
for name, model in models.items():
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    spearman_rho = spearmanr(y_test, y_pred).correlation
    
    results.append({
        'Model': name,
        'MAE ↓': mae,
        'RMSE ↓': rmse,
        'R² ↑': r2,
        'Spearman ρ ↑': spearman_rho
    })

results_df = pd.DataFrame(results).round(3)
display(results_df)

# %% [markdown]
# **Observation:** XGBoost sets the performance ceiling, but the simple OLS and ElasticNet models are remarkably close. This implies the underlying logic of the LLM generating these scores is quite linear.

# %% [markdown]
# ## 8. The Formula — Extracted & Visualized
# 
# Let's extract the formula from the ElasticNet model (which provides a sparse, clean formula).

# %%
# 8a. Extract coefficients
coefs = pd.Series(elastic.coef_, index=FEATURE_COLS)
top_coefs = coefs[coefs.abs() > 0.01].sort_values(key=abs, ascending=False)

formula = "overall_feeling ≈ "
formula_terms = [f"{v:.2f}×{k}" for k, v in top_coefs.items()]
formula += " + ".join(formula_terms) + f" + {elastic.intercept_:.2f}"

print("Extracted Formula:")
print(formula)

# 8b. Coefficient Visualization
plt.figure(figsize=(12, 8))
colors = [ACCENT_COLORS[0] if c > 0 else ACCENT_COLORS[2] for c in top_coefs.values]
sns.barplot(x=top_coefs.values, y=[col.replace('_', ' ').title() for col in top_coefs.index], palette=colors)
plt.title('Feature Weights in the Overall Feeling Formula (ElasticNet)')
plt.show()

# %% [markdown]
# **Observation:** `impactful`, `immersive`, and `story_score` are the biggest positive contributors to a high `overall_feeling`.

# %%
# 8c. Predicted vs Actual Scatter (using ElasticNet)
y_pred_elastic = elastic.predict(X_test)

plt.figure(figsize=(10, 8))
plt.scatter(y_test, y_pred_elastic, c=np.abs(y_test - y_pred_elastic), cmap='magma', alpha=0.7)
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'w--', lw=2)
plt.xlabel('Actual Overall Feeling')
plt.ylabel('Predicted Overall Feeling')
plt.title(f'Predicted vs Actual: Overall Feeling (R² = {r2_score(y_test, y_pred_elastic):.3f})')
plt.colorbar(label='Absolute Residual')
plt.show()

# %% [markdown]
# **Observation:** The predictions align very well with the actual scores, clustering tightly around the diagonal.

# %%
# 8d. SHAP Analysis (XGBoost)
explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test)

plt.figure(figsize=(12, 8))
shap.summary_plot(shap_values, X_test, show=False)
plt.title('SHAP Feature Importance — What Drives Overall Feeling?')
plt.tight_layout()
plt.show()

# Waterfall for the first test movie
idx = 0
plt.figure()
shap.waterfall_plot(shap.Explanation(
    values=shap_values[idx],
    base_values=explainer.expected_value,
    data=X_test.iloc[idx],
    feature_names=[c.replace('_', ' ').title() for c in FEATURE_COLS]
))
plt.show()

# %% [markdown]
# **Observation:** The SHAP summary plot confirms that high values (red) of `impactful` and `immersive` lead to higher SHAP values (pushing the prediction up). The waterfall plot illustrates how exactly the model arrived at the prediction for a specific movie.

# %%
# 8e. Sensitivity Analysis (using OLS)
ols_coefs = pd.Series(ols.coef_, index=FEATURE_COLS).sort_values(ascending=False).head(5)

plt.figure(figsize=(10, 5))
sns.barplot(x=ols_coefs.values, y=[c.replace('_', ' ').title() for c in ols_coefs.index], color=ACCENT_COLORS[1])
plt.title('Sensitivity Analysis: Impact of +1 Point Increase (OLS)')
plt.xlabel('Change in Overall Feeling')
plt.show()

# %% [markdown]
# **Observation:** A one-point increase in `impactful` shifts `overall_feeling` by about +0.27 points (holding everything else constant).
